services:
  grafana:
    image: grafana/grafana:12.4
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USER}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v3.10.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  monitoring-app:
    image: ghcr.io/yagodnik/smarthomemonitoring:f0678b028525d90885ae0b98b768045ac255ca8f
    ports:
      - "9091:9091"
    environment:
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      CREDENTIALS_DIR: "/credentials"
      MASTER_KEY: "1"
    volumes:
      - ./credentials:/credentials
      - ./config.yaml:/config.yaml
      - ./logs:/data/logs
    command: ["-c", "/config.yaml"]